### ISSUE TITLE
Ошибка с ошибками в тестах

### ISSUE THREAD

**Issue by Barsenick** [KadimovRus/calc_go#6]
Здравствуйте. В тестах ожидаются ошибки на английском, но в calculator.go они выдаются на русском. Также я не нашёл в этом же calculator.go обработок ошибок для двух скобок подряд и т.д.  Сделайте просто 2 ошибки: Err422 = ```errors.New("invalid expression")``` и ```Err500 = errors.New("internal server error")```, как и просили в условии

**Comment by KadimovRus** [comment]
Здравствуйте. Не совсем понял по поводу " В тестах ожидаются ошибки на английском, но в calculator.go они выдаются на русском", тесты проходят, в выводе сообщений не нашел ни одного русского слова. По поводу текущей реализации, которая взята из первого задания, объясняли что брать такую какая она есть, главное что тесты которые были даны она прошла. Коды ошибок поправил. Спасибо за комментарии

**Comment by Barsenick** [comment]
Я имел ввиду это 
![image](https://github.com/user-attachments/assets/ff41a78c-4896-44a0-a739-72ab08fcb750)
но теперь всё работает, исправляю балл
